export const HARDWARE_PLATFORM_CONFIG = Object.freeze({
  topY: -0.76,
  components: Object.freeze([
    Object.freeze({
      id: "cpu",
      title: "CPU",
      description: "BOOT EXECUTION",
      position: [-1.35, 0.12, -0.3],
      size: [1.35, 0.22, 1.35],
    }),
    Object.freeze({
      id: "firmware",
      title: "UEFI · SPI FLASH",
      description: "ON-BOARD FIRMWARE",
      position: [-2.35, 0.07, 1.55],
      size: [1.8, 0.12, 0.52],
    }),
    Object.freeze({
      id: "chipset",
      title: "CHIPSET",
      description: "MEMORY CONTROLLER",
      position: [0.55, 0.09, 0.25],
      size: [1.65, 0.16, 1.05],
    }),
    Object.freeze({
      id: "ram",
      title: "RAM",
      description: "MEMORY TRAINING",
      position: [0.25, 0.08, -1.72],
      size: [3, 0.14, 0.46],
    }),
    Object.freeze({
      id: "usb",
      title: "USB · xHCI",
      description: "HOST CONTROLLER",
      position: [2.45, 0.075, 1.55],
      size: [1.45, 0.13, 0.72],
    }),
    Object.freeze({
      id: "devices",
      title: "OTHER DEVICES",
      description: "KERNEL HANDOFF",
      position: [2.65, 0.065, -0.55],
      size: [0.9, 0.11, 1.75],
    }),
  ]),
  busConnections: Object.freeze([
    Object.freeze(["cpu", "chipset"]),
    Object.freeze(["chipset", "ram"]),
    Object.freeze(["chipset", "usb"]),
    Object.freeze(["chipset", "devices"]),
  ]),
  timing: Object.freeze({
    surfacePower: Object.freeze([0, 0.48]),
    silhouettes: Object.freeze([0.12, 0.58]),
    cpuAndFirmware: Object.freeze([0.04, 0.22]),
    firmwareExecution: Object.freeze([0.16, 0.38]),
    chipset: Object.freeze([0.36, 0.56]),
    ram: Object.freeze([0.5, 0.72]),
    memoryTraining: Object.freeze([0.54, 0.78]),
    buses: Object.freeze([0.68, 0.88]),
    usbController: Object.freeze([0.82, 1]),
    usbRead: Object.freeze([0.3, 0.76]),
  }),
});
